name: Deploy to hosting.ua

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup FTP
        uses: SekoiaLab/ftp-action
        with:
          server: free1615.host.od.ua
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: /www/free1615.host.od.ua

