on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: isp2.hosting.ua
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./www/free1615.host.od.ua/
        
    - name: Setup Docker
      run: |
        ssh -i ./ssh_key ${{ secrets.FTP_USERNAME }}@194.54.91.85 "curl -fsSL https://get.docker.com -o get-docker.sh"
        ssh -i ./ssh_key ${{ secrets.FTP_USERNAME }}@194.54.91.85 "sudo sh get-docker.sh"
        ssh -i ./ssh_key ${{ secrets.FTP_USERNAME }}@194.54.91.85 "sudo usermod -aG docker $USER"
        ssh -i ./ssh_key ${{ secrets.FTP_USERNAME }}@194.54.91.85 "sudo systemctl enable docker"
        ssh -i ./ssh_key ${{ secrets.FTP_USERNAME }}@194.54.91.85 "sudo systemctl start docker"
